[package]
name = "rusty-routes-transformer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
osm-io = "0.1.4"
anyhow = "1.0.82"
benchmark-rs = "0.1.1"
simple_logger = "4.3.3"
log = "0.4.21"
regex = "1.10.4"
