# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Run tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run_pre_checks:
    name: Run style and lint checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Check the commit style against the 'conventional commit styling'
        uses: MichaelsJP/action-conventional-commits@master
        with:
          VALID_LABELS: '["feat","fix","docs","style","refactor","test","build","perf","ci","chore","revert","merge","wip"]'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Add conventional release labels
        uses: bcoe/conventional-release-labels@v1.3.0
        with:
          type_labels: '{"feat": "feature", "fix": "fix", "perf": "performance improvement", "revert": "revert", "docs": "documentation", "style": "style", "refactor": "refactor", "test": "test", "build": "build", "ci": "ci", "wip": "wip"}'
          ignored_types: '["chore"]'
          ignore_label: 'ignore-for-release'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  run_boost_tests:
    needs:
      - run_pre_checks
    name: Run Boost tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup compile chain
        run: sudo apt-get -y -qq update && sudo apt-get -y -qq install g++ cmake ninja-build libgdal-dev libproj-dev libosmium-dev libboost-all-dev
      - name: Run tests
        run: |
          cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_MAKE_PROGRAM=/usr/bin/ninja -G Ninja -B ./cmake-build-test  
          cmake --build ./cmake-build-test --target test-osm-transform -j 14
          ./cmake-build-test/test/test-osm-transform 

  run_python_tests:
    needs:
      - run_pre_checks
    strategy:
      # For development set to true to fail fast and not run all versions
      fail-fast: true
      matrix:
        python-version: [ "3.8", "3.9", "3.10", "3.11" ]
        poetry-version: [ "1.4" ]
        os: [ ubuntu-20.04, macos-latest, windows-latest ]
    name: Run & test Python ${{ matrix.python-version }} on ${{ matrix.os }} with Poetry ${{ matrix.poetry-version }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
      - name: Run Poetry action
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: ${{ matrix.poetry-version }}
      - name: View poetry --version
        run: poetry --version
      - name: Install dependencies
        run: poetry install
      - name: Run tests
        run: poetry run pytest
