# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Python CI with Pytest

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  run_pre_checks:
    name: Run style and lint checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Check the commit style against the 'conventional commit styling'
        uses: MichaelsJP/action-conventional-commits@master
        with:
          VALID_LABELS: '["feat","fix","docs","style","refactor","test","build","perf","ci","chore","revert","merge","wip","graphbreak", "apigreak"]'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  run_tests:
    needs:
      - run_pre_checks
    strategy:
      # For development set to true to fail fast and not run all versions
      fail-fast: true
      matrix:
        python-version: [ "3.8", "3.9", "3.10", "3.11" ]
        poetry-version: [ "1.4" ]
        os: [ ubuntu-20.04, macos-latest, windows-latest ]
    name: Run & test Python ${{ matrix.python-version }} on ${{ matrix.os }} with Poetry ${{ matrix.poetry-version }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
      - name: Run Poetry action
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: ${{ matrix.poetry-version }}
      - name: View poetry --version
        run: poetry --version
      - name: Install dependencies
        run: poetry install
      - name: Run tests
        run: poetry run pytest
